### ISSUE TITLE
(Bug): Scale bar parameters are not valid on world map with projection of 4326

### ISSUE THREAD

**Issue by ronenru** [AnSyn/PrivIssues#4]
@yairtawil commented on [Mon Jan 15 2018](https://github.com/AnSyn/ansyn/issues/1081)

---

@asafMasa commented on [Mon Jan 22 2018](https://github.com/AnSyn/ansyn/issues/1081#issuecomment-359434868)

@carmelorr it is a bug in openlayers https://github.com/openlayers/openlayers/issues/7694
that was fixed a week ago, we are waiting for a new version to be deployed

---

@asafMasa commented on [Thu Mar 29 2018](https://github.com/AnSyn/ansyn/issues/1081#issuecomment-377189476)

https://github.com/openlayers/openlayers/issues/8013 i don't think we should use beta, so the bug remains unfixed

**Comment by asafMasa** [comment]
@carmelorr @idanbarak  New OpenLayers version fixed this.
Need to find the time and priority to upgrade to OL 5
